InClass/Controllers/GameController.cs
using InClass.Models; 
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InClass.Controllers
{
    public class GameController : Controller
    {
        private static List<GameModel> MovieList = new List<GameModel>
        {
            new GameModel("Iron Man", 2008, false),
            new GameModel("Blob", 2019, true),
            new GameModel("Man", 2003, true),
            new GameModel("Rando", 1998, false),
            new GameModel("Bam", 2014, false),
            new GameModel("Pop", 2012, true)
        };

        public IActionResult Game()
        {
            return View(MovieList);
        }

        public IActionResult RentMovie()
        {
            return View();
        }
    }
}

InClass/Controllers/HomeController.cs
using InClass.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace InClass.Controllers
{
    public class HomeController : Controller
    {
        private static int count = 0; 
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Home Page - Controller"; 
            DateTime d = DateTime.Now; // gives the date 

            return View();
        }

        public IActionResult Test(int? id) // int? means can hold int or null 
        {
            /*            int id; 

                        if (Request.RouteValues["id"] != null)
                        {
                            var idparam = Request.RouteValues["id"];
                            id = int.Parse(idparam.ToString()); 
                        }*/

            //return Content("id: " + id); // /home/test
            return Content($"id = {id?.ToString() ?? "VERY NULL"}"); 
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Form()
        {
            ViewBag.count = count++; 
            return View();
        }

        [Route("shhh")]
        public IActionResult Secret()
        {
            return View();
        }

        [HttpPost] // makes it so that you can only submit data via post, not get 
        public IActionResult Result(string FirstName)
        {
            //ViewBag.FirstName = Request.Form["FirstName"]; 
            ViewBag.FirstName = FirstName; 
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InClass/Controllers/MovieController.cs
using InClass.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InClass.Interfaces;
using InClass.Data;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InClass.Controllers
{
    [Authorize]
    public class MovieController : Controller
    {
        //IDataAccessLayer dal = new MovieListDAL(); //bad because of hard coding 
        IDataAccessLayer dal; 

        public MovieController(IDataAccessLayer indal) // needed for assignment 
        {
            dal = indal; 
        }

        public IActionResult Index()
        {
            //return View(MovieList);
            //return View(dal.GetMovies(User.FindFirstValue(ClaimTypes.NameIdentifier)).OrderBy(m => m.ReleaseDate).ToList());
            var viewModel = new MoviePage(
                dal.GetMovies(User.FindFirstValue(ClaimTypes.NameIdentifier))
                .OrderBy(m => m.ReleaseDate).ToList(),
                new SelectList(dal.GetGenres(), "Id", "Title")
                );

            return View(viewModel);
        }

        [HttpGet] 
        public IActionResult AddMovie()
        {
            ViewBag.UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var genreList = dal.GetGenres();
            ViewBag.Genres = new SelectList(genreList, "Id", "Title"); 

            return View("MovieForm"); 
        }

        [HttpPost]
        public IActionResult AddMovie(Movie movie)
        {
            if (ModelState.IsValid)
            {
                movie.UserID = User.FindFirstValue(ClaimTypes.NameIdentifier); 
                dal.AddMovie(movie); 
                return Redirect("/Movie/Index"); 
            }

            return View("MovieForm", movie); 
        }

        public IActionResult EditMovie(int id)
        {
            Movie m;
            m = dal.GetMovie(User.FindFirstValue(ClaimTypes.NameIdentifier), id);
            ViewBag.Mode = "Edit";
            ViewBag.ID = id;

            var genreList = dal.GetGenres();
            ViewBag.Genres = new SelectList(genreList, "Id", "Title");

            return View("MovieForm", m);
        }

        // does the save of the existing record 
        public IActionResult UpdateMovie(Movie movie)
        {
            if (ModelState.IsValid)
            {
                dal.UpdateMovie(User.FindFirstValue(ClaimTypes.NameIdentifier), movie);
                return Redirect("/Movie/Index"); 
            }

            return View("MovieForm", movie); 
        }

        public IActionResult DeleteMovie(int? id)
        {
            dal.RemoveMovie(User.FindFirstValue(ClaimTypes.NameIdentifier), id);
            return View("Index", dal.GetMovies(User.FindFirstValue(ClaimTypes.NameIdentifier)));
        }

        public IActionResult MovieForm()
        {
            return View();
        }

        public IActionResult Search(string searchTerm)
        {
            return View();
        }

        public IActionResult DisplayMovie()
        {
            string userID = User.FindFirstValue(ClaimTypes.NameIdentifier); // wacky id 
            string email = User.FindFirstValue(ClaimTypes.Email); // also .Name

            //Movie m = new Movie("Iron Man", 2008, 5.0f); 
            return View("MovieForm");
        }
    }
}

InClass/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Home Page";
}
Contact Page

InClass/Views/Home/Form.cshtml
@{
    ViewData["Title"] = "Home Form"; 
}

<div class="row">
    <div class="col-4">
        <h1>Count: @ViewBag.count</h1>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <!-- <form action="/Home/Result">-->
        <form asp-controller="Home" asp-action="Form">
            <label for="FirstName">Increase Count: --></label>
            <button type="submit">Click Me</button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <form asp-controller="Home" asp-action="Result" method="post">
            <label for="FirstName">First Name:</label><br />
            <input id="FirstName" type="text" name="FirstName" placeholder="First Name" />
            <button type="submit">Submit</button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <form asp-controller="Home" asp-action="Test" method="post">
            <input id="id" type="text" name="id" placeholder="ID" />
            <button type="submit">Submit</button>
        </form>
    </div>
</div>

InClass/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-sm-4 border">
        <!--<a href="~/home/privacy">Privacy</a>-->
        <a asp-controller="Home" asp-action="Privacy">Privacy via Controller/Action</a>
        <a asp-controller="Home" asp-action="Contact"><img src="~/images/shrek.png" width="100" /></a>
        <a asp-controller="Movie" asp-action="Index">Movie Index</a>
        <a asp-controller="Movie" asp-action="AddMovie">Add Movie</a>
        <a asp-controller="Home" asp-action="Test" asp-route-id="15">Test</a>
        <a asp-controller="Game" asp-action="Game">Movie Game</a>
    </div>
    <div class="col-sm-4 border">Row 1 Col 2</div>
    <div class="col-sm-4 border">Row 1 Col 3</div>
</div>
<div class="row">
    <div class="col-sm-8 col-xs-12 border">Row 2 Col 1</div>
    <div class="col-sm-2 col-xs-12 border">Row 2 Col 2</div>
    <div class="col-sm-2 col-xs-12 border">Row 2 Col 3</div>
</div>

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>*@

InClass/Views/Home/Result.cshtml
@if (!string.IsNullOrEmpty(ViewBag.FirstName))
{
    <h1><em>First Name</em>: @ViewBag.FirstName</h1>
}
else
{
    <h5>Aren't you forgetting something, like a first name perhaps?</h5>
}

InClass/Views/Home/Secret.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

secret